require:
  - rubocop-rspec

AllCops:
  Exclude:
    - "db/schema.rb"

Documentation:
  Enabled: false

Rails:
  Enabled: true

RSpec/ExampleLength:
  Max: 16

RSpec/LetSetup:
  Enabled: false

RSpec/MultipleDescribes:
  Enabled: false

RSpec/MultipleExpectations:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/SubjectStub:
  Enabled: false

Style/AlignHash:
  EnforcedColonStyle: table
  EnforcedHashRocketStyle: table

Style/IfUnlessModifier:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/SymbolProc:
  IgnoredMethods:
    - configure
